version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.docker

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env.docker

  db:
    image: postgres:14
    container_name: postgres
    env_file:
      - .env.docker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
