# Use Python base image
FROM python:3.10.15

# Set working directory in the container
WORKDIR /frontend

# Copy only the frontend folder and requirements
COPY ./frontend /frontend
COPY ./requirements.txt /frontend/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port for Streamlit
EXPOSE 8501

# Command to run Streamlit
CMD ["streamlit", "run", "webapp.py", "--server.port=8501", "--server.address=0.0.0.0"]
